# Generated by Django 2.1.2 on 2018-11-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField(blank=True)),
                ('amount', models.FloatField(blank=True)),
                ('delivery_date', models.DateField(blank=True)),
                ('stat', models.CharField(blank=True, choices=[('e', 'encoure'), ('t', 'terminer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.IntegerField()),
                ('reimbursement_date', models.DateField()),
                ('amount', models.BooleanField()),
                ('regulation_number', models.IntegerField()),
                ('method_settlement', models.CharField(max_length=60)),
                ('file_insurance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.FileInsurance')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.Person')),
                ('service_number', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('employee_image', models.ImageField(blank=True, default='employee_image/none/default.png', upload_to='employee_image')),
                ('function', models.CharField(max_length=100)),
                ('fattening_date', models.DateField()),
                ('salary', models.IntegerField()),
            ],
            bases=('insurance.person',),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance.Person')),
                ('relation', models.CharField(choices=[('Girl', 'girl'), ('Son', 'son')], max_length=25)),
                ('employee_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Employee')),
            ],
            bases=('insurance.person',),
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='insurance.Family'),
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to='insurance.Employee'),
        ),
    ]
