# Generated by Django 2.1.3 on 2018-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseinsurance',
            name='file_insurance',
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='file_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='method_settlement',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='regulation_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='reimbursement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Son', 'son')], max_length=25),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='amount',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='ResponseInsurance',
        ),
    ]
