# Generated by Django 2.0.1 on 2018-12-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20181203_0909'),
        ('insurance', '0006_auto_20181207_2139'),
    ]

    operations = [
    ]
