# Generated by Django 2.1.3 on 2018-12-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_merge_20181211_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinsurance',
            name='amount_rreimbursement',
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Relation'),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='amount',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='file_number',
            field=models.IntegerField(default=1),
        ),
    ]
