# Generated by Django 2.1.3 on 2018-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_auto_20181211_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinsurance',
            name='amount_rem',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='stat',
            field=models.CharField(blank=True, choices=[('e', 'encours'), ('t', 'terminer')], max_length=20),
        ),
    ]
