# Generated by Django 2.1.3 on 2018-12-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20181212_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinsurance',
            old_name='reimbursement_date',
            new_name='Repayment_date',
        ),
        migrations.RenameField(
            model_name='fileinsurance',
            old_name='amount_rem',
            new_name='amount_reimbursed',
        ),
    ]
