# Generated by Django 2.1.3 on 2018-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_auto_20181212_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='stat',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
