# Generated by Django 2.1.3 on 2018-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_auto_20181213_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='stat',
            field=models.CharField(blank=True, choices=[('Encours', 'Encours'), ('Terminer', 'Terminer')], max_length=20),
        ),
    ]
