# Generated by Django 2.1.3 on 2018-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20181213_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='amount_reimbursed',
            field=models.IntegerField(null=True),
        ),
    ]
