# Generated by Django 2.1.3 on 2018-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_auto_20181217_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='stat',
            field=models.CharField(blank=True, choices=[('in_progres', 'In progress'), ('finished', 'Finished'), ('refused', 'Refused')], max_length=20),
        ),
    ]
