# Generated by Django 2.1.3 on 2018-12-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20181217_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('in_progres', 'In progress'), ('finished', 'Finished'), ('refused', 'Refused')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileinsurance',
            name='stat',
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.Status'),
        ),
    ]
