# Generated by Django 2.1.3 on 2018-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20181217_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinsurance',
            name='stat',
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='method_settlement_check',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='method_settlement',
            field=models.CharField(choices=[('check', 'Check'), ('devise', 'Devise')], max_length=60, null=True),
        ),
    ]
