# Generated by Django 2.1.3 on 2018-12-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_auto_20181220_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinsurance',
            name='status',
            field=models.CharField(choices=[('in_progres', 'In progress'), ('finished', 'Finished'), ('refused', 'Refused')], default='in_progres', max_length=220),
        ),
    ]
