# Generated by Django 2.1.3 on 2018-12-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_fileinsurance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinsurance',
            old_name='method_settlement_check',
            new_name='check_number',
        ),
    ]
