# Generated by Django 2.1.3 on 2018-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_auto_20181220_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='check_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='status',
            field=models.CharField(choices=[('in_progres', 'In progress'), ('finished', 'Finished'), ('refused', 'Refused')], max_length=220, null=True),
        ),
    ]
