# Generated by Django 2.1.3 on 2018-12-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_auto_20181220_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinsurance',
            name='method_settlement_check',
        ),
        migrations.AddField(
            model_name='fileinsurance',
            name='check_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
