# Generated by Django 2.1.3 on 2018-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_auto_20181220_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='Repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='amount_reimbursed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='method_settlement',
            field=models.CharField(blank=True, choices=[('check', 'Check'), ('devise', 'Devise')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fileinsurance',
            name='regulation_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
