# Generated by Django 2.1.3 on 2018-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_auto_20181225_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='amount',
            field=models.FloatField(),
        ),
    ]
