# Generated by Django 2.1.3 on 2019-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_auto_20181225_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinsurance',
            name='filing_date',
            field=models.DateField(),
        ),
    ]
